<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>PlayMemoMaker</AssemblyName>
    <AssemblyTitle>プレイメモメーカー</AssemblyTitle>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
